<a href="https://colab.research.google.com/github/5ara5t1/course-pytorch-for-deep-learning/blob/s2-pytorch-fundamentals/00_pytorch_fundamentals_encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundmenetals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

Copied by myself, from the following (Udemy Course)[https://www.udemy.com/course/pytorch-for-deep-learning/]

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cpu


## Introduction to Tensors

### Creating tensors
PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [8]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [15]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                        [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [16]:
MATRIX.ndim

2

In [24]:
MATRIX[1,0]

tensor(9)

In [25]:
MATRIX.shape

torch.Size([2, 2])

In [28]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,5,4]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]]])

In [29]:
TENSOR.ndim

3

In [30]:
TENSOR.shape

torch.Size([1, 3, 3])

In [33]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 4]])

In [37]:
TENSOR2 = torch.tensor([[[1,2,3],
          [4,5,6],
          [7,8,9]],
         [[10,11,12],
          [13,14,15],
          [16,17,18]]])

In [38]:
TENSOR2.ndim

3

In [39]:
TENSOR2.shape

torch.Size([2, 3, 3])

In [40]:
TENSOR2[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [41]:
TENSOR2[1]

tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])